### ISSUE TITLE
Error loading pluin

### ISSUE THREAD

**Issue by danewallace** [dgreif/homebridge-ring-alarm#12]
I'm receiving the following error when trying to load the ring-alarm plugin after a successful install. Other plugins load just fine. JSON is valid. Everything launches just fine if plugin Is uninstalled. Node v10.5.0. I appreciate the help. 

Loaded plugin: homebridge-ring-alarm
/usr/local/lib/node_modules/homebridge/lib/server.js:166
      plugin.initializer(this._api);
             ^

TypeError: plugin.initializer is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:166:14)
    at Array.forEach (<anonymous>:null:null)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:140:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

**Comment by dgreif** [comment]
Have you tried the latest version of homebridge?  Looks like this might have been fixed in `v0.4.46` https://github.com/nfarina/homebridge/commit/9b87762d2e9056c61f664316445b31d54ae1a79b

**Comment by dgreif** [comment]
Great, glad to hear that!
