### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by solarbeat** [dgreif/homebridge-ring-alarm#8]
Homebridge 0.4.45
node.js v6.10.2
homebridge-ring-alarm 1.1.0

I install the plugin using "npm i -g homebridge-ring-alarm" -- everything installs fine, no issues. When I start up homebridge, it throws an error on loading the homebridge-ring-alarm plugin:

====================
ERROR LOADING PLUGIN homebridge-ring-alarm:
/usr/local/lib/node_modules/homebridge-ring-alarm/node_modules/ring-api/main.js:7
    email = process.env.RING_USER,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring-alarm/lib/src/ring-alarm-platform.js:11:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring-alarm/lib/index.js:3:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:149:14)
    at Array.forEach (native)
====================

**Comment by dgreif** [comment]
@solarbeat the underlying `ring-api` library is written using some of the newer javascript syntax which won't work with node 6.  Looks like node `8.3.0` is the earliest version that has the necessary features (based on a quick google search, haven't tested to verify).  Let me know if upgrading fixes the issue for you.

**Comment by solarbeat** [comment]
Thanks - upgraded Node and that took care of the issue. If only that didn't break some other plugins. Still, having yours working is significantly better. Thank you so much for taking the time to put this together!
